package com.pchome.hadoopdmp.data.mysql.pojo;
// Generated 2017/6/27 �U�� 03:38:36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmAdGroup generated by hbm2java
 */
@Entity
@Table(name = "adm_ad_group", catalog = "dmp")
public class AdmAdGroup implements java.io.Serializable {

	private Integer id;
	private String adGroup;
	private String name;
	private Date createDate;
	private Date updateDate;
	private Set<AdmAdClass> admAdClasses = new HashSet<AdmAdClass>(0);

	public AdmAdGroup() {
	}

	public AdmAdGroup(String adGroup, String name, Date createDate, Date updateDate) {
		this.adGroup = adGroup;
		this.name = name;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public AdmAdGroup(String adGroup, String name, Date createDate, Date updateDate, Set<AdmAdClass> admAdClasses) {
		this.adGroup = adGroup;
		this.name = name;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.admAdClasses = admAdClasses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ad_group", nullable = false, length = 16)
	public String getAdGroup() {
		return this.adGroup;
	}

	public void setAdGroup(String adGroup) {
		this.adGroup = adGroup;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "admAdGroup")
	public Set<AdmAdClass> getAdmAdClasses() {
		return this.admAdClasses;
	}

	public void setAdmAdClasses(Set<AdmAdClass> admAdClasses) {
		this.admAdClasses = admAdClasses;
	}

}
