package com.pchome.hadoopdmp.data.mysql.pojo;
// Generated 2017/6/28 �U�� 02:12:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmCategoryGroupAnalyze generated by hbm2java
 */
@Entity
@Table(name = " adm_category_group_analyze", catalog = "dmp")
public class AdmCategoryGroupAnalyze implements java.io.Serializable {

	private Integer id;
	private String adGroupId;
	private String userIdType;
	private int adClassCountByHistory;
	private Date createDate;

	public AdmCategoryGroupAnalyze() {
	}

	public AdmCategoryGroupAnalyze(String adGroupId, String userIdType, int adClassCountByHistory, Date createDate) {
		this.adGroupId = adGroupId;
		this.userIdType = userIdType;
		this.adClassCountByHistory = adClassCountByHistory;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ad_group_id", nullable = false, length = 16)
	public String getAdGroupId() {
		return this.adGroupId;
	}

	public void setAdGroupId(String adGroupId) {
		this.adGroupId = adGroupId;
	}

	@Column(name = "user_id_type", nullable = false, length = 5)
	public String getUserIdType() {
		return this.userIdType;
	}

	public void setUserIdType(String userIdType) {
		this.userIdType = userIdType;
	}

	@Column(name = "ad_class_count_by_history", nullable = false)
	public int getAdClassCountByHistory() {
		return this.adClassCountByHistory;
	}

	public void setAdClassCountByHistory(int adClassCountByHistory) {
		this.adClassCountByHistory = adClassCountByHistory;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
