package com.pchome.hadoopdmp.data.mysql.pojo;
// Generated 2017/7/4 �W�� 09:43:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmCategoryAnalyze generated by hbm2java
 */
@Entity
@Table(name = "adm_category_analyze", catalog = "dmp")
public class AdmCategoryAnalyze implements java.io.Serializable {

	private Integer id;
	private Date recodeDate;
	private String adClass;
	private String userIdType;
	private int adClassCountByDay;
	private int sexManCount;
	private int sexWomanCount;
	private int ageRangeCount1to10;
	private int ageRangeCount11to20;
	private int ageRangeCount21to30;
	private int ageRangeCount31to40;
	private int ageRangeCount41to50;
	private int ageRangeCount51to60;
	private int ageRangeCount61to70;
	private int ageRangeCount71to80;
	private int ageRangeCount81to90;
	private int ageRangeCount91to100;
	private Date createDate;
	private Date udpateDate;

	public AdmCategoryAnalyze() {
	}

	public AdmCategoryAnalyze(Date recodeDate, String adClass, String userIdType, int adClassCountByDay,
			int sexManCount, int sexWomanCount, int ageRangeCount1to10, int ageRangeCount11to20,
			int ageRangeCount21to30, int ageRangeCount31to40, int ageRangeCount41to50, int ageRangeCount51to60,
			int ageRangeCount61to70, int ageRangeCount71to80, int ageRangeCount81to90, int ageRangeCount91to100,
			Date createDate, Date udpateDate) {
		this.recodeDate = recodeDate;
		this.adClass = adClass;
		this.userIdType = userIdType;
		this.adClassCountByDay = adClassCountByDay;
		this.sexManCount = sexManCount;
		this.sexWomanCount = sexWomanCount;
		this.ageRangeCount1to10 = ageRangeCount1to10;
		this.ageRangeCount11to20 = ageRangeCount11to20;
		this.ageRangeCount21to30 = ageRangeCount21to30;
		this.ageRangeCount31to40 = ageRangeCount31to40;
		this.ageRangeCount41to50 = ageRangeCount41to50;
		this.ageRangeCount51to60 = ageRangeCount51to60;
		this.ageRangeCount61to70 = ageRangeCount61to70;
		this.ageRangeCount71to80 = ageRangeCount71to80;
		this.ageRangeCount81to90 = ageRangeCount81to90;
		this.ageRangeCount91to100 = ageRangeCount91to100;
		this.createDate = createDate;
		this.udpateDate = udpateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "recode_date", nullable = false, length = 10)
	public Date getRecodeDate() {
		return this.recodeDate;
	}

	public void setRecodeDate(Date recodeDate) {
		this.recodeDate = recodeDate;
	}

	@Column(name = "ad_class", nullable = false, length = 16)
	public String getAdClass() {
		return this.adClass;
	}

	public void setAdClass(String adClass) {
		this.adClass = adClass;
	}

	@Column(name = "user_id_type", nullable = false, length = 5)
	public String getUserIdType() {
		return this.userIdType;
	}

	public void setUserIdType(String userIdType) {
		this.userIdType = userIdType;
	}

	@Column(name = "ad_class_count_by_day", nullable = false)
	public int getAdClassCountByDay() {
		return this.adClassCountByDay;
	}

	public void setAdClassCountByDay(int adClassCountByDay) {
		this.adClassCountByDay = adClassCountByDay;
	}

	@Column(name = "sex_man_count", nullable = false)
	public int getSexManCount() {
		return this.sexManCount;
	}

	public void setSexManCount(int sexManCount) {
		this.sexManCount = sexManCount;
	}

	@Column(name = "sex_woman_count", nullable = false)
	public int getSexWomanCount() {
		return this.sexWomanCount;
	}

	public void setSexWomanCount(int sexWomanCount) {
		this.sexWomanCount = sexWomanCount;
	}

	@Column(name = "age_range_count_1to10", nullable = false)
	public int getAgeRangeCount1to10() {
		return this.ageRangeCount1to10;
	}

	public void setAgeRangeCount1to10(int ageRangeCount1to10) {
		this.ageRangeCount1to10 = ageRangeCount1to10;
	}

	@Column(name = "age_range_count_11to20", nullable = false)
	public int getAgeRangeCount11to20() {
		return this.ageRangeCount11to20;
	}

	public void setAgeRangeCount11to20(int ageRangeCount11to20) {
		this.ageRangeCount11to20 = ageRangeCount11to20;
	}

	@Column(name = "age_range_count_21to30", nullable = false)
	public int getAgeRangeCount21to30() {
		return this.ageRangeCount21to30;
	}

	public void setAgeRangeCount21to30(int ageRangeCount21to30) {
		this.ageRangeCount21to30 = ageRangeCount21to30;
	}

	@Column(name = "age_range_count_31to40", nullable = false)
	public int getAgeRangeCount31to40() {
		return this.ageRangeCount31to40;
	}

	public void setAgeRangeCount31to40(int ageRangeCount31to40) {
		this.ageRangeCount31to40 = ageRangeCount31to40;
	}

	@Column(name = "age_range_count_41to50", nullable = false)
	public int getAgeRangeCount41to50() {
		return this.ageRangeCount41to50;
	}

	public void setAgeRangeCount41to50(int ageRangeCount41to50) {
		this.ageRangeCount41to50 = ageRangeCount41to50;
	}

	@Column(name = "age_range_count_51to60", nullable = false)
	public int getAgeRangeCount51to60() {
		return this.ageRangeCount51to60;
	}

	public void setAgeRangeCount51to60(int ageRangeCount51to60) {
		this.ageRangeCount51to60 = ageRangeCount51to60;
	}

	@Column(name = "age_range_count_61to70", nullable = false)
	public int getAgeRangeCount61to70() {
		return this.ageRangeCount61to70;
	}

	public void setAgeRangeCount61to70(int ageRangeCount61to70) {
		this.ageRangeCount61to70 = ageRangeCount61to70;
	}

	@Column(name = "age_range_count_71to80", nullable = false)
	public int getAgeRangeCount71to80() {
		return this.ageRangeCount71to80;
	}

	public void setAgeRangeCount71to80(int ageRangeCount71to80) {
		this.ageRangeCount71to80 = ageRangeCount71to80;
	}

	@Column(name = "age_range_count_81to90", nullable = false)
	public int getAgeRangeCount81to90() {
		return this.ageRangeCount81to90;
	}

	public void setAgeRangeCount81to90(int ageRangeCount81to90) {
		this.ageRangeCount81to90 = ageRangeCount81to90;
	}

	@Column(name = "age_range_count_91to100", nullable = false)
	public int getAgeRangeCount91to100() {
		return this.ageRangeCount91to100;
	}

	public void setAgeRangeCount91to100(int ageRangeCount91to100) {
		this.ageRangeCount91to100 = ageRangeCount91to100;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "udpate_date", nullable = false, length = 19)
	public Date getUdpateDate() {
		return this.udpateDate;
	}

	public void setUdpateDate(Date udpateDate) {
		this.udpateDate = udpateDate;
	}

}
