package com.pchome.akbdmp.data.mysql.pojo;
// Generated 2018/5/20 �U�� 01:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmAdClass generated by hbm2java
 */
@Entity
@Table(name = "adm_ad_class")
public class AdmAdClass implements java.io.Serializable {

	private Integer id;
	private AdmAdGroup admAdGroup;
	private String adClass;
	private String name;
	private int memidCount;
	private int uuidCount;
	private Date createDate;
	private Date updateDate;

	public AdmAdClass() {
	}

	public AdmAdClass(AdmAdGroup admAdGroup, String adClass, String name, int memidCount, int uuidCount,
			Date createDate, Date updateDate) {
		this.admAdGroup = admAdGroup;
		this.adClass = adClass;
		this.name = name;
		this.memidCount = memidCount;
		this.uuidCount = uuidCount;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "adm_ad_group_id", nullable = false)
	public AdmAdGroup getAdmAdGroup() {
		return this.admAdGroup;
	}

	public void setAdmAdGroup(AdmAdGroup admAdGroup) {
		this.admAdGroup = admAdGroup;
	}

	@Column(name = "ad_class", nullable = false, length = 16)
	public String getAdClass() {
		return this.adClass;
	}

	public void setAdClass(String adClass) {
		this.adClass = adClass;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "memid_count", nullable = false)
	public int getMemidCount() {
		return this.memidCount;
	}

	public void setMemidCount(int memidCount) {
		this.memidCount = memidCount;
	}

	@Column(name = "uuid_count", nullable = false)
	public int getUuidCount() {
		return this.uuidCount;
	}

	public void setUuidCount(int uuidCount) {
		this.uuidCount = uuidCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 0)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
