package com.pchome.akbdmp.data.mysql.pojo;
// Generated 2017/7/17 �U�� 03:41:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmMenu generated by hbm2java
 */
@Entity
@Table(name = "adm_menu", catalog = "dmp")
public class AdmMenu implements java.io.Serializable {

	private Integer menuId;
	private String displayName;
	private String action;
	private Integer parentMenuId;
	private int sort;
	private Date createDate;
	private Date updateDate;

	public AdmMenu() {
	}

	public AdmMenu(String displayName, int sort, Date createDate, Date updateDate) {
		this.displayName = displayName;
		this.sort = sort;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public AdmMenu(String displayName, String action, Integer parentMenuId, int sort, Date createDate,
			Date updateDate) {
		this.displayName = displayName;
		this.action = action;
		this.parentMenuId = parentMenuId;
		this.sort = sort;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "menu_id", unique = true, nullable = false)
	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	@Column(name = "display_name", nullable = false, length = 20)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "action", length = 50)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "parent_menu_id")
	public Integer getParentMenuId() {
		return this.parentMenuId;
	}

	public void setParentMenuId(Integer parentMenuId) {
		this.parentMenuId = parentMenuId;
	}

	@Column(name = "sort", nullable = false)
	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
