package com.pchome.akbdmp.data.mysql.pojo;
// Generated 2018/5/20 �U�� 01:29:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AdmPrivilegeModelMenuRef generated by hbm2java
 */
@Entity
@Table(name = "adm_privilege_model_menu_ref")
public class AdmPrivilegeModelMenuRef implements java.io.Serializable {

	private AdmPrivilegeModelMenuRefId id;

	public AdmPrivilegeModelMenuRef() {
	}

	public AdmPrivilegeModelMenuRef(AdmPrivilegeModelMenuRefId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "modelId", column = @Column(name = "model_id", nullable = false)),
			@AttributeOverride(name = "menuId", column = @Column(name = "menu_id", nullable = false)) })
	public AdmPrivilegeModelMenuRefId getId() {
		return this.id;
	}

	public void setId(AdmPrivilegeModelMenuRefId id) {
		this.id = id;
	}

}
