package com.pchome.akbdmp.data.mysql.pojo;
// Generated 2018/5/20 �U�� 01:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmUser generated by hbm2java
 */
@Entity
@Table(name = "adm_user")
public class AdmUser implements java.io.Serializable {

	private String userEmail;
	private String userPassword;
	private String userName;
	private String depId;
	private String depId2;
	private String status;
	private String note;
	private String modelId;
	private Date updateDate;
	private Date createDate;

	public AdmUser() {
	}

	public AdmUser(String userEmail, String userPassword, String userName, String status, String modelId,
			Date updateDate, Date createDate) {
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.userName = userName;
		this.status = status;
		this.modelId = modelId;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public AdmUser(String userEmail, String userPassword, String userName, String depId, String depId2, String status,
			String note, String modelId, Date updateDate, Date createDate) {
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.userName = userName;
		this.depId = depId;
		this.depId2 = depId2;
		this.status = status;
		this.note = note;
		this.modelId = modelId;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "user_email", unique = true, nullable = false, length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_password", nullable = false, length = 20)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_name", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "dep_id", length = 4)
	public String getDepId() {
		return this.depId;
	}

	public void setDepId(String depId) {
		this.depId = depId;
	}

	@Column(name = "dep_id2", length = 4)
	public String getDepId2() {
		return this.depId2;
	}

	public void setDepId2(String depId2) {
		this.depId2 = depId2;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "note", length = 50)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "model_id", nullable = false, length = 3)
	public String getModelId() {
		return this.modelId;
	}

	public void setModelId(String modelId) {
		this.modelId = modelId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 0)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
