package com.pchome.akbdmp.data.mysql.pojo;
// Generated 2018/5/20 �U�� 01:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KdclStatisticsBehavior generated by hbm2java
 */
@Entity
@Table(name = "kdcl_statistics_behavior")
public class KdclStatisticsBehavior implements java.io.Serializable {

	private Integer id;
	private String idType;
	private String storedata;
	private String serviceType;
	private String behavior;
	private int rank;
	private String sex;
	private int age;
	private String adClass;
	private int kdclRequest;
	private int dmpResponse;
	private int infoResponse;
	private int pv;
	private int ck;
	private float hitRate;
	private float ctr;
	private String recordDate;
	private Date updateDate;
	private Date createDate;

	public KdclStatisticsBehavior() {
	}

	public KdclStatisticsBehavior(String idType, String storedata, String serviceType, String behavior, int rank,
			String sex, int age, String adClass, int kdclRequest, int dmpResponse, int infoResponse, int pv, int ck,
			float hitRate, float ctr, String recordDate, Date updateDate, Date createDate) {
		this.idType = idType;
		this.storedata = storedata;
		this.serviceType = serviceType;
		this.behavior = behavior;
		this.rank = rank;
		this.sex = sex;
		this.age = age;
		this.adClass = adClass;
		this.kdclRequest = kdclRequest;
		this.dmpResponse = dmpResponse;
		this.infoResponse = infoResponse;
		this.pv = pv;
		this.ck = ck;
		this.hitRate = hitRate;
		this.ctr = ctr;
		this.recordDate = recordDate;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "id_type", nullable = false, length = 50)
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	@Column(name = "storedata", nullable = false, length = 1)
	public String getStoredata() {
		return this.storedata;
	}

	public void setStoredata(String storedata) {
		this.storedata = storedata;
	}

	@Column(name = "service_type", nullable = false, length = 20)
	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	@Column(name = "behavior", nullable = false, length = 20)
	public String getBehavior() {
		return this.behavior;
	}

	public void setBehavior(String behavior) {
		this.behavior = behavior;
	}

	@Column(name = "rank", nullable = false)
	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	@Column(name = "sex", nullable = false, length = 1)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "ad_class", nullable = false, length = 20)
	public String getAdClass() {
		return this.adClass;
	}

	public void setAdClass(String adClass) {
		this.adClass = adClass;
	}

	@Column(name = "kdcl_request", nullable = false)
	public int getKdclRequest() {
		return this.kdclRequest;
	}

	public void setKdclRequest(int kdclRequest) {
		this.kdclRequest = kdclRequest;
	}

	@Column(name = "dmp_response", nullable = false)
	public int getDmpResponse() {
		return this.dmpResponse;
	}

	public void setDmpResponse(int dmpResponse) {
		this.dmpResponse = dmpResponse;
	}

	@Column(name = "info_response", nullable = false)
	public int getInfoResponse() {
		return this.infoResponse;
	}

	public void setInfoResponse(int infoResponse) {
		this.infoResponse = infoResponse;
	}

	@Column(name = "pv", nullable = false)
	public int getPv() {
		return this.pv;
	}

	public void setPv(int pv) {
		this.pv = pv;
	}

	@Column(name = "ck", nullable = false)
	public int getCk() {
		return this.ck;
	}

	public void setCk(int ck) {
		this.ck = ck;
	}

	@Column(name = "hit_rate", nullable = false, precision = 4)
	public float getHitRate() {
		return this.hitRate;
	}

	public void setHitRate(float hitRate) {
		this.hitRate = hitRate;
	}

	@Column(name = "ctr", nullable = false, precision = 4)
	public float getCtr() {
		return this.ctr;
	}

	public void setCtr(float ctr) {
		this.ctr = ctr;
	}

	@Column(name = "record_date", nullable = false, length = 10)
	public String getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(String recordDate) {
		this.recordDate = recordDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 0)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
