package com.pchome.akbdmp.data.mysql.pojo;
// Generated 2018/5/20 �U�� 01:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KdclStatisticsReport generated by hbm2java
 */
@Entity
@Table(name = "kdcl_statistics_report")
public class KdclStatisticsReport implements java.io.Serializable {

	private Integer id;
	private String recordDate;
	private int memidBehaviorClick;
	private int memidBehaviorSite;
	private int uuidBehaviorClick;
	private int uuidBehaviorSite;
	private int totalRequest;
	private int memidRequest;
	private int memidResponse;
	private int memidInfo;
	private int memidPv;
	private int memidCk;
	private float memidHitRate;
	private float memidCtr;
	private int uuidRequest;
	private int uuidResponse;
	private int uuidInfo;
	private int uuidPv;
	private int uuidCk;
	private float uuidHitRate;
	private float uuidCtr;
	private Date updateDate;
	private Date createDate;

	public KdclStatisticsReport() {
	}

	public KdclStatisticsReport(String recordDate, int memidBehaviorClick, int memidBehaviorSite, int uuidBehaviorClick,
			int uuidBehaviorSite, int totalRequest, int memidRequest, int memidResponse, int memidInfo, int memidPv,
			int memidCk, float memidHitRate, float memidCtr, int uuidRequest, int uuidResponse, int uuidInfo,
			int uuidPv, int uuidCk, float uuidHitRate, float uuidCtr, Date updateDate, Date createDate) {
		this.recordDate = recordDate;
		this.memidBehaviorClick = memidBehaviorClick;
		this.memidBehaviorSite = memidBehaviorSite;
		this.uuidBehaviorClick = uuidBehaviorClick;
		this.uuidBehaviorSite = uuidBehaviorSite;
		this.totalRequest = totalRequest;
		this.memidRequest = memidRequest;
		this.memidResponse = memidResponse;
		this.memidInfo = memidInfo;
		this.memidPv = memidPv;
		this.memidCk = memidCk;
		this.memidHitRate = memidHitRate;
		this.memidCtr = memidCtr;
		this.uuidRequest = uuidRequest;
		this.uuidResponse = uuidResponse;
		this.uuidInfo = uuidInfo;
		this.uuidPv = uuidPv;
		this.uuidCk = uuidCk;
		this.uuidHitRate = uuidHitRate;
		this.uuidCtr = uuidCtr;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "record_date", nullable = false, length = 10)
	public String getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(String recordDate) {
		this.recordDate = recordDate;
	}

	@Column(name = "memid_behavior_click", nullable = false)
	public int getMemidBehaviorClick() {
		return this.memidBehaviorClick;
	}

	public void setMemidBehaviorClick(int memidBehaviorClick) {
		this.memidBehaviorClick = memidBehaviorClick;
	}

	@Column(name = "memid_behavior_site", nullable = false)
	public int getMemidBehaviorSite() {
		return this.memidBehaviorSite;
	}

	public void setMemidBehaviorSite(int memidBehaviorSite) {
		this.memidBehaviorSite = memidBehaviorSite;
	}

	@Column(name = "uuid_behavior_click", nullable = false)
	public int getUuidBehaviorClick() {
		return this.uuidBehaviorClick;
	}

	public void setUuidBehaviorClick(int uuidBehaviorClick) {
		this.uuidBehaviorClick = uuidBehaviorClick;
	}

	@Column(name = "uuid_behavior_site", nullable = false)
	public int getUuidBehaviorSite() {
		return this.uuidBehaviorSite;
	}

	public void setUuidBehaviorSite(int uuidBehaviorSite) {
		this.uuidBehaviorSite = uuidBehaviorSite;
	}

	@Column(name = "total_request", nullable = false)
	public int getTotalRequest() {
		return this.totalRequest;
	}

	public void setTotalRequest(int totalRequest) {
		this.totalRequest = totalRequest;
	}

	@Column(name = "memid_request", nullable = false)
	public int getMemidRequest() {
		return this.memidRequest;
	}

	public void setMemidRequest(int memidRequest) {
		this.memidRequest = memidRequest;
	}

	@Column(name = "memid_response", nullable = false)
	public int getMemidResponse() {
		return this.memidResponse;
	}

	public void setMemidResponse(int memidResponse) {
		this.memidResponse = memidResponse;
	}

	@Column(name = "memid_info", nullable = false)
	public int getMemidInfo() {
		return this.memidInfo;
	}

	public void setMemidInfo(int memidInfo) {
		this.memidInfo = memidInfo;
	}

	@Column(name = "memid_pv", nullable = false)
	public int getMemidPv() {
		return this.memidPv;
	}

	public void setMemidPv(int memidPv) {
		this.memidPv = memidPv;
	}

	@Column(name = "memid_ck", nullable = false)
	public int getMemidCk() {
		return this.memidCk;
	}

	public void setMemidCk(int memidCk) {
		this.memidCk = memidCk;
	}

	@Column(name = "memid_hit_rate", nullable = false, precision = 4)
	public float getMemidHitRate() {
		return this.memidHitRate;
	}

	public void setMemidHitRate(float memidHitRate) {
		this.memidHitRate = memidHitRate;
	}

	@Column(name = "memid_ctr", nullable = false, precision = 4)
	public float getMemidCtr() {
		return this.memidCtr;
	}

	public void setMemidCtr(float memidCtr) {
		this.memidCtr = memidCtr;
	}

	@Column(name = "uuid_request", nullable = false)
	public int getUuidRequest() {
		return this.uuidRequest;
	}

	public void setUuidRequest(int uuidRequest) {
		this.uuidRequest = uuidRequest;
	}

	@Column(name = "uuid_response", nullable = false)
	public int getUuidResponse() {
		return this.uuidResponse;
	}

	public void setUuidResponse(int uuidResponse) {
		this.uuidResponse = uuidResponse;
	}

	@Column(name = "uuid_info", nullable = false)
	public int getUuidInfo() {
		return this.uuidInfo;
	}

	public void setUuidInfo(int uuidInfo) {
		this.uuidInfo = uuidInfo;
	}

	@Column(name = "uuid_pv", nullable = false)
	public int getUuidPv() {
		return this.uuidPv;
	}

	public void setUuidPv(int uuidPv) {
		this.uuidPv = uuidPv;
	}

	@Column(name = "uuid_ck", nullable = false)
	public int getUuidCk() {
		return this.uuidCk;
	}

	public void setUuidCk(int uuidCk) {
		this.uuidCk = uuidCk;
	}

	@Column(name = "uuid_hit_rate", nullable = false, precision = 4)
	public float getUuidHitRate() {
		return this.uuidHitRate;
	}

	public void setUuidHitRate(float uuidHitRate) {
		this.uuidHitRate = uuidHitRate;
	}

	@Column(name = "uuid_ctr", nullable = false, precision = 4)
	public float getUuidCtr() {
		return this.uuidCtr;
	}

	public void setUuidCtr(float uuidCtr) {
		this.uuidCtr = uuidCtr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 0)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 0)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
